task:
  name: CMake / build-FreeBSD
  freebsd_instance:
    image_family: freebsd-13-1
  install_script: pkg install -y cmake llvm-devel gmake git xorg
  script: git submodule update --init --recursive && mkdir build && cmake -B build && cmake --build build
  
task:
  name: Linux ARM64 Build
  arm_container:
    image: alpine:latest
  install_script: apk update && apk add --update cmake build-base make clang git libx11-dev
  script: git submodule update --init --recursive && mkdir build && cmake -B build && cmake --build build
