task:
  name: CMake / build-freebsd-amd64
  freebsd_instance:
    image_family: freebsd-13-1
  install_script: pkg install -y cmake llvm-devel gmake git xorg
  script: git submodule update --init --recursive && mkdir build && cmake -B build && cmake --build build
  
task:
  name: CMake / build-linux-arm64
  arm_container:
    image: ubuntu:latest
  install_script: apt update && apt upgrade && apt install xorg-dev cmake build-essentials git
  script: git submodule update --init --recursive && mkdir build && cmake -B build && cmake --build build
