freebsd_instance:
  image_family: freebsd-13-1

task:
  name: FreeBSD
  install_script: pkg install -y cmake llvm-devel gmake git xorg
  script: git submodule update --init --recursive && mkdir build && cmake -B build && cmake --build build
  
  
