name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build-win64:
    if: "contains(github.event.head_commit.message, '[ci]') || github.event_name == 'release'"
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Configure CMake
      run: |
        git submodule update
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
 
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build-macos:
    if: "contains(github.event.head_commit.message, '[ci]') || github.event_name == 'release'"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Configure CMake
      run: |
        git submodule update
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
 
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build-ubuntu:
    if: "contains(github.event.head_commit.message, '[ci]') || github.event_name == 'release'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Configure CMake
      run: |
        git submodule update
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
 
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}